
MSG (ERR_BADPARAM,	"Parameter option '%s' not recognised")
MSG (ERR_BINFILE,	"Error in binary file")
MSG (ERR_LINKFILE,	"link file error")
MSG (ERR_NOMEMORY,	"Out of memory\nuse % option (-% with cc) to increase memory allocation")
MSG (ERR_OPENFILE,	"Cannot open binary file: '%s'")
MSG (ERR_OPENLIST,	"Cannot open list_file '%s' for writing")
MSG (ERR_OPENWRITE, "Cannot open '%s' for writing")
MSG (ERR_ORGFOUND,	"ORG encountered")
MSG (ERR_PROGERR,	"Should not occur")
MSG (ERR_PROGXREF,	"Error resolving an XREF")
MSG (ERR_RELOCTAB,	"Relocation Table problem")
MSG (ERR_RLLVERSION,"Invalid RLL version '%s'")
MSG (ERR_SECTIONID, "Illegal section id $%04.4x (%s)")
MSG (ERR_SYMBOLID,	"Illegal symbol id")
MSG (ERR_TABLE, 	"Table overflow (%s)")
MSG (ERR_TEXTOPTION,"Option '-%c %s' not recognised")
MSG (ERR_UDATABSS,	"UDATA/BSS section problem")
MSG (ERR_UNKNOWN,	"Unrecognized error/message type %d !!")
MSG (ERR_WRITEFILE, "Cannot write file correctly")
MSG (ERR_XREFOPERS, "Too many operands in XREF")
